// <auto-generated />
namespace ProjektMove.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Person_Info : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Person_Info));
        
        string IMigrationMetadata.Id
        {
            get { return "201807171145467_Person_Info"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
